### ISSUE TITLE
Bitbucket cloud 401 not authorized

### ISSUE THREAD

**Issue by tiagogba** [snyk-tech-services/snyk-scm-contributors-count#75]
Hi,

I'm facing issue when try to run script in my bitbucket cloud and return 401, like this:

![image](https://user-images.githubusercontent.com/4753833/198629003-a8837026-2c14-4e16-bdf4-90d1d59192e7.png)

I could see that bitbucket.org deprecated in your API auth using user and pass in your api.(https://bitbucket.org/blog/deprecating-atlassian-account-password-for-bitbucket-api-and-git-activity)

**Comment by lili2311** [comment]
HI @tiagogba that's correct, Bitbucket now require you generate a token differently to use with APIs. Please regenerate the token as an app password and try again, the docs you shared show the steps expected to help with this.

**Comment by tiagogba** [comment]
i don't understand, because snyk script username and password is required.
I generated app authorization and replace with my password but received 401 yet.

could you send me example how to execute this script?

**Comment by GoDllkE** [comment]
I'm having the same issue running with the mac binary. Followed the bitbucket-cloud walkthrough and got the same 401 issue. The same user/password works in other integrations, for further reference.

Any ideias of what may be wrong or fixes?

**Comment by lili2311** [comment]
Hi @tiagogba and @GoDllkE 

This change has been in place for a while, please can I confirm you are using your `username` with the app password? It
 won't work with email anymore. You can find your username here: https://bitbucket.org/account/settings/ 
<img width="490" alt="CleanShot 2022-11-03 at 16 35 53@2x" src="https://user-images.githubusercontent.com/2911613/199780160-1ba7c1d1-f575-448b-9760-99a72c562add.png">

I've just checked run this locally using the username & password for Bitbucket Cloud and it is working as expected.

`bitbucket-cloud --user lili-snyk --password xxxxxxxx` you can see full instructions here: https://github.com/snyk-tech-services/snyk-scm-contributors-count/blob/main/docs/bitbucket-cloud-example.md

**Comment by GoDllkE** [comment]
Thanks, it worked for me. Never thought that bitbucket would set a different Username from what I used.
