### ISSUE TITLE
Incomplete results due to default page size in retrieveMonitoredReposBySourceType

### ISSUE THREAD

**Issue by JamesTyzack** [snyk-tech-services/snyk-scm-contributors-count#84]
The `retrieveMonitoredReposBySourceType` in Snyk\Index.js does not specify a result limit or do any paging on the underlying Snyk REST API that retrieves monitored repos. This causes incomplete results when counting contributors, as it is only going back to count contributors in the source control for the first 10 monitored repos; 10 being the default page size of the underlying Snyk API.

The following is used to call the Snyk API (line 117):

`/orgs/${orgs[i].id}/targets?origin=${SourceType[sourceType]}&version=${snykApiVersion}`

Without a `&limit` parameter or paging logic, it will return only 10 results.

**Comment by mitechie** [comment]
Linked to Jira Issue GROWTH-1934

**Comment by rikhal** [comment]
I've bumped into this issue as well. Opened a PR #85 to contribute the fix I've made to load all data.

**Comment by logangeorgebrown** [comment]
Hi Folks, we've merged a fix for this is v2.16.0. Please let us know if you have any further problems
